### PR TITLE
Tek830 a 35 investigate how to connect UI elements with model

### PR DESCRIPTION
**Pull request by RezaAmanii**
This pull request contains following changes and updates:
- Refactored the AptLayout.py class 
- Refactored the App.py which solved the threating issue
- Added some new methods to the aptLayout.py 
- Connected Time_Slider, schedule to the AptLayout.py (Observer pattern)
- AptLayout check events and triggers the right method

### CODE REVIEW

**Review by filipkauffeldt — CHANGES_REQUESTED** [review]
This does not follow the architecture we talked about. It is not possible to use physical lights instead of a demo gui with this solution. Should probably use the interfaces we designed and the follow the architecture we discussed.
bild

**Comment by RezaAmanii** [comment]
> This does not follow the architecture we talked about. It is not possible to use physical lights instead of a demo gui with this solution. Should probably use the interfaces we designed and the follow the architecture we discussed. bild

Nothing that we discussed and agree on it, as my knowldege it was only a suggestion on how to connect the model and UI element, if my approach was not working. I remember we talked about having a Light system or something like that, but the idea was to use that if my approach was not wokring.

**Comment by filipkauffeldt** [comment]
> > This does not follow the architecture we talked about. It is not possible to use physical lights instead of a demo gui with this solution. Should probably use the interfaces we designed and the follow the architecture we discussed. bild
> 
> Nothing that we discussed and agree on it, as my knowldege it was only a suggestion on how to connect the model and UI element, if my approach was not working. I remember we talked about having a Light system or something like that, but the idea was to use that if my approach was not wokring.

I agree, but this does not work if we want to extend it to be able to use another method to display the model. Like #13 where want to connect to physical lights.

**Comment by BooloCaptain** [comment]
as it is right now, lamps seem to not be toggled correctly if you skip ahead

**Pull request closed without merging**
